name: Publish to PyPI
on:
  workflow_dispatch:
    inputs:
      args:
        description: Additional args to run "pdm publish"
        type: string
        default: ''
  push:
    tags: [ v*.** ]
  release:
    types: [ published ]
jobs:
  pypi-publish:
    name: Upload tag / release to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
      - name: Publish package distributions to PyPI
        run: pdm publish ${{ inputs.args }}
